/**
 * Human-readable names for common ISO 4217 currency codes, used to label
 * the Combobox's options. The exchange-rate API returns ~160 currency
 * codes with no names attached — this map covers the currencies users are
 * actually likely to search for; any code without an entry here just
 * falls back to displaying its bare code, which is still fully functional.
 */
export const CURRENCY_NAMES: Record<string, string> = {
  USD: 'US Dollar',
  EUR: 'Euro',
  GBP: 'British Pound',
  JPY: 'Japanese Yen',
  CNY: 'Chinese Yuan',
  AUD: 'Australian Dollar',
  CAD: 'Canadian Dollar',
  CHF: 'Swiss Franc',
  HKD: 'Hong Kong Dollar',
  NZD: 'New Zealand Dollar',
  SEK: 'Swedish Krona',
  NOK: 'Norwegian Krone',
  DKK: 'Danish Krone',
  SGD: 'Singapore Dollar',
  INR: 'Indian Rupee',
  LKR: 'Sri Lankan Rupee',
  PKR: 'Pakistani Rupee',
  BDT: 'Bangladeshi Taka',
  NPR: 'Nepalese Rupee',
  AED: 'UAE Dirham',
  SAR: 'Saudi Riyal',
  QAR: 'Qatari Riyal',
  KWD: 'Kuwaiti Dinar',
  BHD: 'Bahraini Dinar',
  OMR: 'Omani Rial',
  ILS: 'Israeli New Shekel',
  TRY: 'Turkish Lira',
  RUB: 'Russian Ruble',
  ZAR: 'South African Rand',
  EGP: 'Egyptian Pound',
  NGN: 'Nigerian Naira',
  KES: 'Kenyan Shilling',
  GHS: 'Ghanaian Cedi',
  BRL: 'Brazilian Real',
  MXN: 'Mexican Peso',
  ARS: 'Argentine Peso',
  CLP: 'Chilean Peso',
  COP: 'Colombian Peso',
  PEN: 'Peruvian Sol',
  KRW: 'South Korean Won',
  IDR: 'Indonesian Rupiah',
  MYR: 'Malaysian Ringgit',
  THB: 'Thai Baht',
  VND: 'Vietnamese Dong',
  PHP: 'Philippine Peso',
  TWD: 'New Taiwan Dollar',
  PLN: 'Polish Zloty',
  CZK: 'Czech Koruna',
  HUF: 'Hungarian Forint',
  RON: 'Romanian Leu',
  UAH: 'Ukrainian Hryvnia',
  ISK: 'Icelandic Krona',
  BGN: 'Bulgarian Lev',
  HRK: 'Croatian Kuna',
};
